#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "guacamole"
name = "Guacamole"
description.en = "Remote access solution"
description.fr = "Solution d'accès à distance"

version = "1.6.0~ynh1"

maintainers = ["Jules Bertholet"]

[upstream]
license = "Apache-2.0"
website = "https://guacamole.apache.org/"
admindoc = "https://guacamole.apache.org/doc/gug/"
code = "https://github.com/apache/guacamole-server"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "200M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/guacamole"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]
    [resources.sources]

    [resources.sources.tomcat9]
    url = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz"
    sha256 = "ee86ee179493e610358b23a0f79ba70b9e76ade71157aada9ac7cdcdcdbe35f5"

    [resources.sources.server]
    url = "https://downloads.apache.org/guacamole/1.6.0/source/guacamole-server-1.6.0.tar.gz"
    sha256 = "8bc45675da96d7b6f39728160181e3d4ff3c08f460f6d26de5805b642bf13f2b"

    [resources.sources.client]
    url = "https://downloads.apache.org/guacamole/1.6.0/binary/guacamole-1.6.0.war"
    sha256 = "b41ceb1e2df010b54db563e0b00edb8d5fe9f073c6168462e4c978df0fc6e716"
    format = "zip"
    extract = false
    rename = "guacamole.war"

    [resources.sources.auth-header]
    url = "https://downloads.apache.org/guacamole/1.6.0/binary/guacamole-auth-header-1.6.0.tar.gz"
    sha256 = "54c6ea944aab5153bda20401fa28400128ad89606b57027bee2127327b65f958"

    [resources.sources.auth-ldap]
    url = "https://downloads.apache.org/guacamole/1.6.0/binary/guacamole-auth-ldap-1.6.0.tar.gz"
    sha256 = "b07f27adc370324108527b6929f61d93880026d57c1033064bd1c55b881c7497"

    [resources.sources.auth-jdbc]
    url = "https://downloads.apache.org/guacamole/1.6.0/binary/guacamole-auth-jdbc-1.6.0.tar.gz"
    sha256 = "97bc5fd3d67d25c0e98a475d1dfd308a037859f549fac47171c723b7a7039366"

    [resources.sources.mariadb-java-client]
    url = "https://dlm.mariadb.com/4550298/Connectors/java/connector-java-2.7.13/mariadb-java-client-2.7.13.jar"
    sha256 = "20f01b9bf7eb8abb87e6af32641dd0cfd2784cfe37a74720cb487960f911278f"
    format = "whatever"
    extract = false
    rename = "mariadb-java-client.jar"

    [resources.ports]
    # change to not conflit with tomcat10 from debain repo if any
    main.default = 8088
    guacd.default = 4822

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "acl",
        "build-essential",
        "libcairo2",
        "libjpeg62-turbo-dev",
        "libpng-dev",
        "libtool-bin",
        "libossp-uuid-dev",
        "libavcodec-dev",
        "libavformat-dev",
        "libavutil-dev",
        "libswscale-dev",
        "libpango1.0-dev",
        "libssh2-1-dev",
        "libtelnet-dev",
        "libvncserver-dev",
        "libwebsockets-dev",
        "libpulse-dev",
        "libssl-dev",
        "libvorbis-dev",
        "libwebp-dev",
        "default-jre",
    ]

packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "freerdp2-dev";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "freerdp3-dev";
    fi
    """

    [resources.database]
    type = "mysql"
