#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service="$app-guacd" --action="stop" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="stop" --log_path="/var/log/$app/$tomcat_version.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MOVE TOMCAT WEBAPP FOLDER
#=================================================

if [ $change_path -eq 1 ]; then
    ynh_script_progression "Moving Tomcat webbapp folder..."

    old_path_tomcat="$(tomcat_path_for_path "$old_path")"
    new_path_tomcat="$(tomcat_path_for_path "$new_path")"
    mv "$install_dir/$tomcat_version/webapps/$old_path_tomcat.war" \
        "$install_dir/$tomcat_version/webapps/$new_path_tomcat.war"
fi

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-guacd" --action="start" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="start" --log_path="/var/log/$app/$tomcat_version.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
