#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service="$app-guacd" --action="stop" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="stop" --log_path="/var/log/$app/tomcat.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MOVE TOMCAT WEBAPP FOLDER
#=================================================

if [ $change_path -eq 1 ]; then
	ynh_script_progression "Moving Tomcat webbapp folder..."

	old_path_tomcat="$old_path"
	if [ "$old_path_tomcat" == "/" -o -z "$old_path_tomcat" ]; then
		old_path_tomcat="ROOT"
	fi
	new_path_tomcat="$new_path"
	if [ "$new_path_tomcat" == "/" -o -z "$new_path_tomcat" ]; then
		new_path_tomcat="ROOT"
	fi

	mv "$install_dir/var/lib/tomcat9/webapps/$old_path_tomcat" "$install_dir/var/lib/tomcat9/webapps/$new_path_tomcat"
fi

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting systemd services..."

ynh_systemctl --service="$app-guacd" --action="start" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="start" --log_path="/var/log/$app/tomcat.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
