#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Stopping system tomcat..."

# Guacamole depends on Apache Tomcat.
# But installing Tomcat from the Debian repos automatically enables and starts it.
# So we stop and disable it, unless Tomcat was already enabled or started by the user beforehand
if systemctl is-enabled $tomcat_version --quiet 2>/dev/null; then
	systemctl disable $tomcat_version --quiet
fi
if systemctl is-active $tomcat_version --quiet 2>/dev/null; then
	systemctl stop $tomcat_version --quiet
fi

#=================================================
# CREATE DEDICATED USERS
#=================================================
ynh_script_progression "Configuring system users..."

ynh_system_user_create --username="$app-guacd" --groups="$app"
ynh_system_user_create --username="$app-tomcat" --groups="$app"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCES
#=================================================
ynh_script_progression "Setting up source files..."

setup_sources

mkdir -p "/var/log/$app/tomcat/" "/var/log/$app/guacd/" "/var/log/$app/tomcat/"
mkdir -p "$install_dir/etc/"
ln -s -f "$install_dir/etc/$tomcat_version" "$install_dir/var/lib/$tomcat_version/conf"
ln -s -f "/var/log/$app/tomcat/" "$install_dir/var/lib/$tomcat_version/logs"
ln -s -f "/var/cache/$app-$tomcat_version" "$install_dir/var/lib/$tomcat_version/work"

#=================================================
# ADD CONFIGURATIONS
#=================================================

ynh_config_add --template="guacamole.properties" --destination="$install_dir/etc/guacamole/guacamole.properties"

ynh_replace --match="8080" --replace="$port" --file="$install_dir/etc/tomcat9/server.xml"

_set_permissions

#=================================================
# COMPILE GUACD
#=================================================
ynh_script_progression "Compiling guacd..."

pushd "$install_dir/.guacd-src"
	LDFLAGS="-lrt" ./configure --enable-allow-freerdp-snapshots --prefix="$install_dir" --datadir="$install_dir" --with-freerdp-plugin-dir="$install_dir/lib/x86_64-linux-gnu/freerdp2"
	ynh_hide_warnings make -j $(nproc)
	ynh_hide_warnings make install
popd

#=================================================
# FINISH SETTING UP DATABASE
#=================================================
ynh_script_progression "Setting up database files..."

ynh_replace --match="guacadmin" --replace="$admin" -f "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"
ynh_replace --match="CA458A7D494E3BE824F5E1E175A1556C0F8EEF2C2D7DF3633BEC4A29C4411960" --replace="$(hexdump -n 32 -e '4/4 "%08X"' /dev/urandom)" -f "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"
ynh_replace --match="FE24ADC5E11E2B25288D1704ABE67A79E342ECC26064CE69C5B3177795A82264" --replace="$(hexdump -n 32 -e '4/4 "%08X"' /dev/urandom)" -f "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"

ynh_mysql_db_shell < "$install_dir/etc/guacamole/extensions/mysql-schema/001-create-schema.sql"
ynh_mysql_db_shell < "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"
ynh_safe_rm "$install_dir/etc/guacamole/extensions/mysql-schema"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-guacd" --template="guacd.service"
yunohost service add "$app-guacd" --description="Guacamole server" --log="/var/log/$app/guacd.log"

ynh_config_add_systemd --service="$app-tomcat" --template="tomcat.service"
yunohost service add "$app-tomcat" --description="Guacamole client" --log="/var/log/$app/tomcat.log"

ynh_config_add_logrotate "/var/log/$app/tomcat/catalina.out"

ynh_config_add_fail2ban --logpath="/var/log/syslog" --failregex='o.a.g.r.auth.AuthenticationService - Authentication attempt from <HOST> for user "[^"]*" failed\.$'

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="$app-guacd" --action="start" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="start" --log_path="/var/log/$app/tomcat.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
