#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CREATE DEDICATED USERS
#=================================================
ynh_script_progression "Configuring system users..."

# Create system users
ynh_system_user_create --username="$app-guacd" --groups="$app" --home_dir="$data_dir/$app-guacd"
ynh_system_user_create --username="$app-tomcat" --groups="$app" --home_dir="$data_dir/$app-tomcat"

_create_home "$app-guacd" "$data_dir/$app-guacd"
_create_home "$app-tomcat" "$data_dir/$app-tomcat"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing Tomcat 9..."

install_tomcat

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCES
#=================================================
ynh_script_progression "Setting up source files..."

setup_sources

#=================================================
# COMPILE GUACD
#=================================================
ynh_script_progression "Building guacd..."

build_server

# _set_permissions

mkdir -p "$install_dir/server/etc/"
ln -s -f "$install_dir/server/etc/$tomcat_version" "$install_dir/$tomcat_version/conf"
ynh_safe_rm "$install_dir/$tomcat_version/logs"
ln -s -f "/var/log/$app/$tomcat_version/" "$install_dir/$tomcat_version/logs"
ln -s -f "/var/cache/$app-$tomcat_version" "$install_dir/$tomcat_version/work"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="guacamole.properties" --destination="$install_dir/etc/guacamole/guacamole.properties"

# ynh_replace --match="8080" --replace="$port" --file="$install_dir/server/etc/$tomcat_version/server.xml"
ynh_safe_rm "$install_dir/$tomcat_version/conf/server.xml"
ynh_config_add --template="server.xml" --destination="$install_dir/$tomcat_version/conf/server.xml"

# _set_permissions

#=================================================
# FINISH SETTING UP DATABASE
#=================================================
ynh_script_progression "Setting up database files..."

ynh_replace --match="guacadmin" --replace="$admin" -f "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"
ynh_replace --match="CA458A7D494E3BE824F5E1E175A1556C0F8EEF2C2D7DF3633BEC4A29C4411960" --replace="$(hexdump -n 32 -e '4/4 "%08X"' /dev/urandom)" -f "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"
ynh_replace --match="FE24ADC5E11E2B25288D1704ABE67A79E342ECC26064CE69C5B3177795A82264" --replace="$(hexdump -n 32 -e '4/4 "%08X"' /dev/urandom)" -f "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"

ynh_mysql_db_shell < "$install_dir/etc/guacamole/extensions/mysql-schema/001-create-schema.sql"
ynh_mysql_db_shell < "$install_dir/etc/guacamole/extensions/mysql-schema/002-create-admin-user.sql"
ynh_safe_rm "$install_dir/etc/guacamole/extensions/mysql-schema"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create dedicated systemd configs
ynh_config_add_systemd --service="$app-guacd" --template="guacd.service"
yunohost service add "$app-guacd" --description="Guacamole server" --log="/var/log/$app/guacd.log"

ynh_config_add_systemd --service="$app-tomcat" --template="tomcat.service"
yunohost service add "$app-tomcat" --description="Guacamole client" --log="/var/log/$app/$tomcat_version.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
ynh_config_add_logrotate "/var/log/$app/$tomcat_version/catalina.out"
# FIXME: chmod useful?
chmod -R g+rw "/var/log/$app"
chown -R "$app-guacd:$app-guacd" "/var/log/$app/guacd/"
chown -R "$app-tomcat:$app-tomcat" "/var/log/$app/$tomcat_version/"

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/syslog" --failregex='o.a.g.r.auth.AuthenticationService - Authentication attempt from <HOST> for user "[^"]*" failed\.$'

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting $app's systemd services..."

# Start systemd services
ynh_systemctl --service="$app-guacd" --action="start" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="start" --log_path="/var/log/$app/$tomcat_version.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
