#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_fail2ban

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status "$app-guacd" >/dev/null; then
    yunohost service remove "$app-guacd"
fi
ynh_config_remove_systemd "$app-guacd"

if ynh_hide_warnings yunohost service status "$app-tomcat" >/dev/null; then
    yunohost service remove "$app-tomcat"
fi
ynh_config_remove_systemd "$app-tomcat"

ynh_config_remove_nginx

#=================================================
# REMOVE VARIOUS FILES
#=================================================

# Legacy cleanup
if [ -e "/etc/logrotate.d/$app-$tomcat_version" ]; then
    rm "/etc/logrotate.d/$app-$tomcat_version"
fi

#=================================================
# REMOVE DEDICATED USERS
#=================================================
ynh_script_progression "Removing the dedicated system users..."

# Delete system users, homedirs will be deleted with data_dir
ynh_system_user_delete --username="$app-guacd"
ynh_system_user_delete --username="$app-tomcat"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
