#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICES
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service="$app-guacd" --action="stop" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="stop" --log_path="/var/log/$app/tomcat.log"

#=================================================
# CREATE DEDICATED USERS
#=================================================
#REMOVEME? ynh_script_progression "Making sure dedicated system user exists..."

# Create dedicated users (if not existing)
ynh_system_user_create --username="$app-guacd"
ynh_system_user_create --username="$app-tomcat"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	setup_sources
fi

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

# Guacamole depends on Apache Tomcat.
# But installing Tomcat from the Debian repos automatically enables and starts it.
# So we stop and disable it, unless Tomcat was already enabled or started by the user beforehand

tomcat_enabled=""
tomcat_active=""
if [ "$(systemctl cat tomcat9 --quiet)" ]; then
	if (systemctl is-enabled tomcat9 --quiet); then
		tomcat_enabled=1
	fi
	if (systemctl is-active tomcat9 --quiet); then
		tomcat_active=1
	fi
fi

if [ ! $tomcat_enabled ]; then
	systemctl disable tomcat9 --quiet
fi
if [ ! $tomcat_active ]; then
	systemctl stop tomcat9 --quiet
fi

#=================================================
# COMPILE GUACD
#=================================================
ynh_script_progression "Compiling guacd..."

pushd "$install_dir/.guacd-src"
	LDFLAGS="-lrt" ./configure --enable-allow-freerdp-snapshots --prefix="$install_dir" --datadir="$install_dir" --with-freerdp-plugin-dir="$install_dir/lib/x86_64-linux-gnu/freerdp2"
	ynh_hide_warnings env LDFLAGS="-lrt" make
	ynh_hide_warnings env LDFLAGS="-lrt" make install
popd

#=================================================
# SETUP TOMCAT
#=================================================

mkdir -p "$install_dir/etc/"
ln -s -f "$install_dir/etc/tomcat9" "$install_dir/var/lib/tomcat9/conf"
ln -s -f "/var/log/$app/tomcat/" "$install_dir/var/lib/tomcat9/logs"
ln -s -f "/var/cache/$app-tomcat9" "$install_dir/var/lib/tomcat9/work"

#=================================================
# CREATE LOG DIRS
#=================================================

mkdir -p "/var/log/$app/tomcat/" "/var/log/$app/guacd/" "/var/log/$app/tomcat/"

#=================================================
# UPDATE CONFIG FILES
#=================================================

ynh_config_add --template="guacamole.properties" --destination="$install_dir/etc/guacamole/guacamole.properties"

ynh_replace --match="8080" --replace="$port" --file="$install_dir/etc/tomcat9/server.xml"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

# Create dedicated systemd configs
ynh_config_add_systemd --service="$app-guacd" --template="guacd.service"
ynh_config_add_systemd --service="$app-tomcat" --template="tomcat.service"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

_set_permissions

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Upgrading logrotate configuration..."

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate "/var/log/$app/tomcat/catalina.out"

#=================================================
# INTEGRATE SERVICES IN YUNOHOST
#=================================================
ynh_script_progression "Integrating services in YunoHost..."

yunohost service add "$app-guacd" --description="Guacamole server" --log="/var/log/$app/guacd.log"
yunohost service add "$app-tomcat" --description="Guacamole client" --log="/var/log/$app/tomcat.log"

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting systemd services..."

ynh_systemctl --service="$app-guacd" --action="start" --log_path="/var/log/$app/guacd.log"
ynh_systemctl --service="$app-tomcat" --action="start" --log_path="/var/log/$app/tomcat.log"

#=================================================
# UPGRADE FAIL2BAN
#=================================================
ynh_script_progression "Reconfiguring Fail2Ban..."

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/syslog" --failregex='o.a.g.r.auth.AuthenticationService - Authentication attempt from <HOST> for user "[^"]*" failed\.$'

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
